name: frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/**'

defaults:
  run:
    working-directory: frontend

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: aws-actions/configure-aws-credentials@v2
    #   env:
    #     USER_ID: ${{ secrets.USER_ID }}
      with:
        role-to-assume: "arn:aws:iam::776811705601:role/github-actions-frontend-deploy"
        aws-region: ap-northeast-1

    - run: aws s3 sync . s3://github-actions-storage-0001 --exact-timestamps --region ap-northeast-1
