name: backend

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: "10 12 * * *"

defaults:
  run:
    working-directory: frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - run: aws s3 sync . s3://github-actions-storage-0001 --exact-timestamps --region ap-northeast-1